### ISSUE TITLE
requirejs is searching for modules in wrong place: http://localhost:8000/portfolio/81/js/common.js  (404)

### ISSUE THREAD

**Issue by 4meFirst** [jrburke/requirejs#1228]
I'm using requirejs with laravel, and everything works fine with a simple url like  http://localhost:8000/portfolio, http://localhost:8000/contacts..., but it start to search modules in wrong place when I add more steps to url address like: http://localhost:8000/portfolio/view -> will search in http://localhost:8000/portfolio/js/common.js , http://localhost:8000/portfolio/view/test -> http://localhost:8000/portfolio/view/js/common.js

**Comment by jrburke** [comment]
You can set the baseUrl to be a path that starts with a `/` to make sure it is always the same baseUrl no matter what sub-path is used in the URL. So, something like baseUrl: '/js' should be enough.

Then, for r.js optimizer builds, you can override the baseUrl in the build config to be a relative path just for the build to complete, since using '/js' with the optimizer will not work (it will be relative to the root of the file system instead of a domain).
