### ISSUE TITLE
Modifications to dependency variable persist

### ISSUE THREAD

**Issue by mcladyz** [jrburke/requirejs#1240]
Not sure if this is intended behaviour, but:

If a module returns a function and that function modifies a variable associated with that module's dependency, the variable retains the modifications if the module is reloaded.

Test-Gist: https://gist.github.com/mcladyz/ff073c8111b04c20b5be

**Comment by mcladyz** [comment]
What about this one?

**Comment by jrburke** [comment]
If you are talking about how `resource` is null on the second function invocation for this module:

```javascript
	  define( 'func', [ 'resource' ], function( resource ) {
	      return function() {
		  console.log( resource );
		  resource = null;
	      };
	  });
```

That is correct, but just because of normal JavaScript rules. The first call modifies the local variable `resource` to point to null. That local variable, since it is outside the function returned, retains the value assigned to it.

Closing as a discussion ticket, feel free to continue discussion here.
