### ISSUE TITLE
modules listed in define sometimes (not always) return undefined instead of module instance

### ISSUE THREAD

**Issue by imissyouso** [jrburke/requirejs#1260]
Hi. First at all thanks for your job.
After few days finding problem in my code (using google) I decided to write here.
I have client side JS which use requirejs as base of architecture. But sometimes this system is not works correct, I see messages that modules which was listed in 'define' sometimes returns undefined value, it is cause of crash my application. But it happens not always, on the average every 5 page reloading and in different parts of the system. Below I attached real project structure and code of files where error can be thrown.
![lolol](https://cloud.githubusercontent.com/assets/1973760/5637730/02370346-9629-11e4-88ef-00dfea7a5e1c.png)

app.js
```javascript
requirejs.config({
    paths: {
        jquery: 'Lib/jquery-1.11.0.min',
        socketio: 'http://localhost:81/socket.io/socket.io',
        jquerytmpl: 'Lib/jquery.tmpl.min',
        jqueryui: 'https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min',
        jquerymultiselect: 'Lib/jquery-ui/jquery.multiselect.min',
        css: 'Lib/requirecss',
        cookie: 'Lib/jquery.cookie',
        bootstrap: "http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min",
        flatui: "Lib/flat-ui-pro.min"
    },
    waitSeconds: 200,
    shim: {
        socketio: {
            exports: 'io'
        },
        flatui: {
            exports: '$',
            deps: ['jquery']
        },
        cookie: {
            exports: '$',
            deps: ['jquery']
        }
    }
});
require(['jquery', 'Router'], function($, Router){
    Router.startRouting();
});
```
Router.js
```javascript
define(['jquery'], function($) {
    var routes = [{uri: /^\/$/, controller: 'MainPageController'},
        {uri: /^\/[a-z0-9_]+\/?$/, controller: 'PublicPageController'},
        {uri: /^\/public\/add\/?$/, controller: 'PublicAddPageCOntroller'}];

    function startRouting() {
        var currentURI = window.location.pathname;

        $.each(routes, function(k, v) {
            if (v.uri.test(currentURI)) {
                loadController(v.controller);
            }
        });
    }

    function loadController(controllerName) {
        require(['Controllers/' + controllerName], function(controller) {
            controller.init();
        });
    }

    return {
        startRouting: startRouting
    };
});
```

Controllers/PublicPageController.js
```javascript
define(['jquery', 'socketio', 'Modules/ChatModule', 'Modules/NotificationModule', 'Modules/StatusModule', 'Modules/PageBuilderModule', 'Entity/Mediator'], function ($, io, ChatModule, NotificationModule, StatusModule, PageBuilderModule, mediator) {
    function init() {
        /**
         * Connect to socket.io server
         */
        var socket = io('http://localhost:81/?token=' + token);
        /**
         * init modules
         */
        var notificationModule = new NotificationModule(socket, mediator);
        var pageBuilderModule = new PageBuilderModule(socket, mediator);
        var chatModule = new ChatModule(socket, mediator);
        var statusModule = new StatusModule(socket, mediator);

    }
    return {init: init};
});
```

Modules/NotificationModule.js
```javascript
define(['jquery', 'Entity/SystemNotification', 'Entity/ChatRequestNotification', 'Entity/Notifications', 'Entity/ChatRequestNotificationAcceptedByPair', 'Entity/UriModifier'], function ($, SystemNotification, ChatRequestNotification, Notifications, ChatRequestNotificationAcceptedByPair, UriModifier) {

    function NotificationModule(socket, mediator) {
        var notifications = new Notifications(socket);
        var that = this;
        this.addNotification = function (data) {
            switch (data.type) {
                case 1:
                    var notification = new SystemNotification(data.id, data.fields.message, data.fields.from, socket);
                    break;
                case 2:
                    var notification = new ChatRequestNotification(data.id, data.fields.from, UriModifier.getCurrentSlug(), socket,
                            function (err, data) {
                                mediator.publish('chatRequestAccepted', err, data, notification);
                            },
                            function (err, data) {
                                mediator.publish('chatRequestDeclined', err, data, notification);
                            });
                    break;
                case 3:
                    var notification = new ChatRequestNotificationAcceptedByPair(data.id, data.fields.from, socket,
                            function (err, data) {
                                mediator.publish('chatRequestStarted', err, data, notification);
                            }, function (err, data) {
                                //chatRequestCanceled
                                mediator.publish('chatRequestCanceled', err, data, notification);
                            });
                    break;
            }
            if(notification){
                notifications.push(notification);
            }
            
        };
        
        socket.on('notificationsLoaded', function (data) {
            $.each(data.notifications, function (k, v) {
                that.addNotification(v);
            });
        });
    }
    return NotificationModule;

});

```

Entity/SystemNotification
```javascript
define(['jquery','Entity/Notification','Views/SystemNotificationView'], function ($, Notification, SystemNotificationView) {
    function SystemNotification(id, message, from, socket) {
        var parent = Notification.call(this, id, socket);
        parent.setView(new SystemNotificationView(id, 'Системное уведомление', message, from));
    };
    
    return SystemNotification;
});
```

Entity/Notification
```javascript
define(['jquery'], function ($) {
    return function (id, socket) {
        var that = this;
        this.append = function () {
            this.view.append();
        };
        this.close = function () {
            this.view.close();
            socket.emit('closeNotification', {id: id});
        };
        this.getId = function () {
            return id;
        };

        return {
            setView: function (v) {
                that.view = v;
                $(that.view).on('close', function () {
                    that.close();
                });
            }
        };
    };
});
```

index.html
```html
<script data-main="/app" src="/Lib/requirejs.js"></script>
```
Steps through goes execution flow are next:
1. app.js init requrejs options and run Router.js
2. Router detects current page and runs fit controller (in this example it is PublicPageController)
3. In controller runs Modules (pay attention for NotificationModule)
4. Notification module registers callback for socketio event 'notificationsLoaded' which returns notification data. In registered callback NotificationModule tries to create notification objects (for example Entity/SystemNotification)
5. Each Notification it is child of base class Entity/Notification
6. In Entity/SystemNotification constructor I try to call var parent = Notification.call(this, id, socket); for inheritance realization, but sometimes Notification is UNDEFINED! It is problem. 

The above was described only for 1 case of error, there are much more places where I have the same error (undefined module) 

My requirejs version is RequireJS 2.1.15

Help me pls, where is the problem? 

Regards
Andrei Vorobiov

**Comment by imissyouso** [comment]
Problem was solved by changing RequireJS 2.1.15 to 2.0. So, it is still actual for 2.1.15

**Comment by tkissing** [comment]
Not sure if this is related, but using the same "exports" value for multiple shim configuration will lead to non-deterministic results.
The exports value for jQuery plugins should be one of the properties the plugin adds to the jQuery global, e.g. jQuery.cookie for jQuery.cookie or jQuery.fn.emulateTransitionEnd for bootstrap

**Comment by jrburke** [comment]
If you are testing this by rapidly reloading the page multiple times in a row, the error is likely for the page instance that just got replaced by the browser. 

Sometimes, depending on the browser, it does not know to completely shut off JS execution for a discarded page, and I have seen some code execute after the page unload starts and some objects have been destroyed.

I would expect though that the new page load should work even if you see an error in the log from the previous load. Perhaps this explains the behavior you are seeing?

**Comment by darcyzagonel** [comment]
Same problem. Downgraded to 2.0.

**Comment by morphar** [comment]
Same problem here, except it doesn't help to downgrade to 2.0.0 - I have also tried 2.0.6.

@jrburke I tried to trigger the error without fast reloads and I can still do that.
Tried waiting at least a couple of seconds after everything has loaded.
I have also noticed the problem occurring randomly, when just using the site.

My guess: It seems like a premature attempt at calling define, sometime failing due to the script not being fully loaded.

**Comment by cesarzagonel** [comment]
Avoided requirejs.

**Comment by ernestopye** [comment]
+1 - Having this issue as well. Happens when opening new tabs, even switching browsers. It seems to sporadically return undefined for certain dependencies. No network errors. The files are loaded up fine, but they never seem to be parsed. For example

Test.js
```
define(['jquery'], function($) {
  console.log('hey i was loaded!');

  return { 
    test: 123 
  };
});
```

That console message will sometimes not run at all, even though Test.js was loaded (checked via Network tab in Chrome dev tools). This of course results in getting undefined if I try to load Test as a dependency within another module. It isn't one particular module either, it seems to vary quite a bit.

**Comment by amenadiel** [comment]
I'm sure there are other issues at play here, but for starters I wouldn't reccomend using CDNs unless you load it manually in your HTML before requireJS. This in regard to jQuery specifically, but might apply to other libraries.

What has worked for me was to concatenate jQuery and RequireJS in one file, so when I require main.js I can count on jQuery to be loaded already.

Second, jQuery plugins shouldn't export anything unless you actually return $ at the end of the file, and even in that case, remember jQuery puts itself in the global namespace. Tampering with $ will probably mess up everything.

**Comment by ernestopye** [comment]
For us, the issue ended up being related to a JS bundle coming in from another service. It included multiple concatenated+minified jquery plugins, some of which had AMD support. They had unnamed define() calls, and this was causing issues. I've worked with them since to resolve this. Is there a way to increase verbosity to help troubleshoot this type of issue? It seemed that this only failed on some occasions, but not others. Sometimes I'd get the mismatch error which was very telling, but only rarely. Most of the time I'd just get undefined when doing a require() call on certain modules I had created.

**Comment by chrisknoll** [comment]
Is there any place do add a onLoad callback in the require.config() params, such that when the loader requests a module, i tcan fire a callback and then we can console.log some of the information?  This would be a handy debug tool.  If we could actually define a 'lifecycle' for module loading (ie: moduleRequested, moduleLoaded, dependencyResolved, etc) we could understand better the order of calls under the covers, and get to the bottom of why a module might be scrambled during a dependency load (such as, modules in bundles impacting other externally loaded modules).

**Comment by jrburke** [comment]
This seems to be turning into a catch-all bug for problems with undefined dependencies. This could be for a few different reasons, and it is best to share an example app with the issue to figure out what is exactly the problem. Some possibilities:

* There is a [dependency cycle](http://requirejs.org/docs/api.html#circular) is in the code, which could explain the original poster's problem, given that event/Notification depends on event/Notifications, and some other notification-related stuff, and if any of those dependencies rely on event/Notification there could be an issue, could result in an undefined.
* A bundle of modules including unnamed defines will definitely be a problem.
* More esoteric and hopefully less likely, but sometimes a browser add-on or plugin is messing with HTTP requests. I know this was an issue at least in one case with a Chrome browser extension. I do not know which one, just know the reporter said that turning off the add-ons fixed the issue.

As for hooks for different stages of loading, due to the above, they will likely not be uniformly helpful. There are no hooks in a require.config call though. You could try overriding [requirejs.load](https://github.com/jrburke/requirejs/blob/edd2f929212a717caf47b27dab2575c4d3bed48c/require.js#L1853), and [requirejs.onResourceLoad](https://github.com/jrburke/requirejs/wiki/Internal-API:-onResourceLoad) might give some hints, but with things like bundled modules and some unnamed defines, the unnamed ones are particularly hard to track given the lack of a name. [xrayquire](https://github.com/requirejs/xrayquire) was also an attempt at a modifier script that would try to detect some misconfiguration issues too, but I have not kept it up.

Given that this issue is collecting things from multiple core underlying issues, I am going to close it for now, and for the original post I suspect the cycle issue. However, if there is a test case for the original post, feel free to point to it and we can reopen as needed. For the other issues, it would be best to have separate issues with their own test cases.
