### ISSUE TITLE
Why ReuireJS loads the same file which was redefined in shim section?

### ISSUE THREAD

**Issue by nervgh** [jrburke/requirejs#1270]
Hi!

* Project tree https://yadi.sk/i/q98Klg_8eBusa (screenshort)
* Config
```js
requirejs.config({
    baseUrl: "/js",
    shim: {
        "polyfills": [
            "polyfills/console-sham.min" // <-- NOT AMD
        ]
    },
    deps: [
        "bootstrap"
    ]
});
```
* Loading queue https://yadi.sk/i/KoRhekgOeBv6a (screenshort)
* Contents of `bootstrap.js`
```js
require(['polyfills'], function() {
    //console.log();
});
```

**Questions**:
1. Why ReuireJS loaded **js/polyfills.js** file?
2. How can I avoided this behavior?

Thanks.

**Comment by jrburke** [comment]
The shim config, using an array as a value, means that the module with the ID of "polyfills" depends on "polyfills/console-shame.min", and since bootstrap.js asks for "polyfills", it will load the dependencies for "polyfills" and then "polyfills" itself.

If you want "polyfills" to just be an alias for "polyfills/console.sham.min" and to not load "polyfills" (which is located at "js/polyfills.js" according to that config), then [map config](http://requirejs.org/docs/api.html#config-map) is the config option to use instead of "shim".

Closing as a discussion ticket, feel free to continue discussion here.

**Comment by nervgh** [comment]
@jrburke, very grateful :smiley:
