### ISSUE TITLE
WINDOWS PHONE : Module name "affix" has not been loaded yet for context: _

### ISSUE THREAD

**Issue by divstudio** [jrburke/requirejs#1279]
Hello

I got `Module name "affix" has not been loaded yet for context: _` error, but ONLY on windows phone 8.1 !!!
I'm using "shim multi-page" config.

It's working everywhere else (IE11/10 desktop, FF, Chrome desktop/mobile, Android, iOs etc...)

Thx

**Comment by jrburke** [comment]
That usually means the module was not an explicit dependency (via a string literal) for the module that wanted to use it, and a dynamic `require(something)` for it was done in the module. It may work in some situations if 'affix' just happens to also load because another module depends on it, but depending on how fast or slow either file IO or network IO, it could fail.

So without seeing the specific module that failed, that is my best guess at the problem. Closing as a discussion ticket, but feel free to continue discussion here.
