### ISSUE TITLE
require sugar syntax does not work on 

### ISSUE THREAD

**Issue by eleith** [jrburke/requirejs#1290]
we hit the "not loaded" bug while using the sugar syntax recently in production, using our minified scripts. below is a boiled down sample to show how to reproduce the bug.

```javascript
define(function(require){function makeHttps(url){return url.replace(/^http:\/\//i,"https://")}var x=require("js/lib/x");return{}});
```

when the script loads, require throws a "no loaded" error when it sees `js/lib/x`

however if we were to do this instead:

```javascript
define(function(require){var x=require("js/lib/x");function makeHttps(url){return url.replace(/^http:\/\//i,"https://")}return{}});
```

`js/lib/x` will load as expected and no error is thrown.

this is using requirejs 2.1.15

as you can see, our minification moved all our require calls to the bottom. my guess is the parsing to figure out the dependencies of a script using the sugar syntax interacts incorrectly with the `makeHttps` regex parts.

**Comment by jrburke** [comment]
You are correct, this is a limitation of the string based parsing done at runtime. The "remove comments" regexp finds the // in the URL and thinks it is a comment, because it does not have enough context to know it is in a string. 

The tradeoff to avoid this kind of issue is embedding something like an AST generator in require.js which can be quite large and slows down the parsing of the scripts too. I'm open to suggestions on how to improve the situation via a regexp-based solution, but in the past I have found this hard to work out without a much bigger code solution.

In general, I recommend for the sugar syntax is to make sure extract all the dependencies during an r.js optimizing build, via [normalizeDirDefines](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L132). That assumes the use of the r.js optimizer though. Ideally another tool understanding AMD would have this feature, since it is a general help for minification cases.

For this specific case, another workaround would be to construct the string as `"https:/" + "/"`. Definitely a workaround, but would be enough if tooling was not an option.

I am going to close as a known limitation, but would consider solution that were lightweight to fix it, so feel free to continue discussion here.

**Comment by eleith** [comment]
the other workaround is just to use the original `define([dep1, dep2, dep3], ` wrapper.

what we need know is a way to automatically determine when we need to do this.

however, we normally do bundle up our stuff, so the hope is we don't hit this often enough...

**Comment by jrburke** [comment]
Right, that is the other way to work around it, if not using a build tool that will take care of the issue. The normalizeDirDefines essentially makes sure to insert the dependency array in the define call so that function tostring scanning is not needed, and the requirejs optimizer uses a full ast when parsing for dependencies, so it will not have a problem finding the dependency.

**Comment by eleith** [comment]
another option, we do a lot of processing of each of our assets so it is simple for us to add more layers.

one of those layers is to wrap all our files in define calls using `amwrap`. if we could have something similar like `requireNormalize`, we could process all our files beforehand, and then not worry whether or not it gets bundled up, because we will have done the processing beforehand.

this would also help us with the creation of sourcemaps, because i now noticed that many of our sources are broken, because this step introduces a change in the source, but our sourcemap still has the old source content in it.

i'll poke around in requirejs to see if you have this already modularized so we can import it as a task.

**Comment by jrburke** [comment]
transform.toTransport does the work:
https://github.com/jrburke/r.js/blob/master/build/jslib/transform.js#L27

You can use the internal r.js modules using the useLib API:
https://github.com/jrburke/r.js/blob/master/build/tests/tools/uselib/parseDeps.js

That test example asks for the 'parse' internal module, but asking for 'transform' instead should give you the module. `transform.toTransport('', moduleName, path, contents) may be enough for what you need.

**Comment by eleith** [comment]
perfect! i already have something working, thanks so much.
