### ISSUE TITLE
baseUrl does not use different host

### ISSUE THREAD

**Issue by joseph-jja** [jrburke/requirejs#1323]
Setting baseUrl to an assets host does not serve the assets from that asset host?

**Comment by jrburke** [comment]
I am sorry, this is not enough information to understand the problem. If the problem is that baseUrl does not seem to be applied, it is important to check that the script with the baseUrl setting is evaluated before any other modules start to load. Setting the baseUrl to a remote host is supported though. Some loader plugins, like the text loader plugin have special considerations for that case, but plain JS module scripts should not have a problem.

Going to close for now, but feel free to add more information and we can reopen as needed.

**Comment by joseph-jja** [comment]
So I have a script src='http://assets.somecompany.com/optimized_file_with_require_and_config.js' which loads first, then after that I have 
<script>
require.config( { baseUrl: 'http://assets.somecompany.com' }); 
</script>
Then the rest of the page require statements here.  The first file is an optimized base script that has things that are commonly used.  What I am noticing is that nothing is loading form my assets.somecompany.com site :( everything is loading from the http://www.somecompany.com instead of my baseUrl.  I'm using require 2.1.14.  Does that help?  

I don't want to put somecomany name here.

**Comment by jrburke** [comment]
If it is like this:

```html
<script src="optimized_file_with_require_and_config.js"></script>
<script>
  require(["something/else"], function(somethingElse) {

  });
</script>
```

That will work fine as long as the first script does not have an "async" or "defer" attribute set and the requirejs.config() in optimized_file_with_require_and_config.js is not inside a define() call.

Note that baseUrl does not apply for some dependency IDs, so if the second script tag does this:

```javascript
require(['some/other/resource.js'], function(res) {});
```

That will not be resolved relative to the baseUrl. Details in the [this API section](http://requirejs.org/docs/api.html#jsfiles). For that case, it is best to use module IDs instead of URL strings.

**Comment by joseph-jja** [comment]
```
<script src="optimized_file_with_require_and_config.js"></script>
<script>
  require.config({
    baseUrl: 'http://someother.asset.host'
  });
</script>
// html html html and then
<script>
  require(["something/else"], function(somethingElse) {

  });
</script>
```
so the above is more like what I have.  in any case the require.config call is before the other require statements

**Comment by jrburke** [comment]
If modules in optimized_file_with_require_and_config.js trigger loading of modules and they are expected to use baseUrl of 'http://someother.asset.host', then I can see that failing, as the requests for those network loaded dependencies can go out before that require.config call for http://someother.asset.host is called.

To avoid that, you can set up a require object with initial config before the script that includes requirejs:

```html
<script>
  var require = {
    baseUrl: 'http://someother.asset.host'
  };
</script>
<script src="optimized_file_with_require_and_config.js"></script>

// html html html and then
<script>
  require(["something/else"], function(somethingElse) {

  });
</script>
```

**Comment by joseph-jja** [comment]
Ok, I am doing this and it still does not work.  Should that be 

var require = { 
    config: { 
      baseUrl: 'http://someother.asset.host'
   }
}

**Comment by jrburke** [comment]
Do not put baseUrl in a "config" object, just at the top level of the require object.

**Comment by joseph-jja** [comment]
So I currently don't have it in a config.
