### ISSUE TITLE
removing body script elements

### ISSUE THREAD

**Issue by rickdog** [jrburke/requirejs#1336]
require is removing my body's script elements:

```html
<!DOCTYPE html>
<html>
    <head>
        <script data-main="app" src="lib/require.js"></script>
    </head>
    <body>
        <h1>Hello World</h1>
		<script>
			alert(1);
		</script>
    </body>
</html>
```
in inspector:
```
$("script")
<script src="lib/require.js" data-main="app">
```

**Comment by jrburke** [comment]
Oops, I saw volojs/create-template/#4 and answered over there first, but to repeat from there (and probably if you have follow up comments, post here instead of over there):

This seems to be a behavior that $() is doing. If I do `document.getElementsByTagName('script')`, I see that script as the last one in that list.

So closing, as I do not believe this is related to requirejs or this template, but something with the $() function.
