### ISSUE TITLE
[question] Packaging third party libs

### ISSUE THREAD

**Issue by chchrist** [jrburke/requirejs#1339]
Hello,

What is the best way to use r.js to bundle all the third party libs into one file and then require it into your project? Is that a good practise? Is anyone doing it?

**Comment by jrburke** [comment]
It really depends on the project. There is the [single file approach](http://requirejs.org/docs/optimization.html#onejs), a [whole directory optimization](http://requirejs.org/docs/optimization.html#wholeproject) that can have multiple build layers, and an example of a [multi-page kind of project](https://github.com/requirejs/example-multipage).

All of those are acceptable, really just depends on the project, what it is trying to accomplish, how much lazy loading can be done vs what is needed up front.

Closing as a discussion ticket, feel free to continue discussion here.

**Comment by chchrist** [comment]
I'd like to have two files a lib.js that contains all third party libraries and a main.js which contains the application's code. There I will require libs and main and then initialise my app. Will I have any problem with require being able to find the libs inside the libs.js?

**Comment by jrburke** [comment]
The multi-page example has a setup like that, so that is a good thing to look at. You could also use [bundles config](http://requirejs.org/docs/api.html#config-bundles) to list all the module IDs that are in lib. 

The downside with bundles config at the moment is that the r.js optimizer does not have a way to automatically generate a bundles config to be used by the loader after a build. So the multi-page approach of two nested require([]) calls might be the way to go.

**Comment by meenakshi1969** [comment]
Hi All,
Is there any way to include third-party party libraries which are defined in path inside requirejs config.I have tried to do that but we cant expose them in bundle.
