### ISSUE TITLE
Samsung SmartTV 2010-2011: Load timeout for modules

### ISSUE THREAD

**Issue by boromo** [jrburke/requirejs#1344]
I'm trying to use requirejs for building SmartTV applications, but I've realized that there is an issue with Samsung devices 2010-2011. These devices are using maple browser, and it looks like they are missing some support for requirejs. 
Is there a way to make require run on these devices?
Thanks!

**Comment by jrburke** [comment]
It would be helpful to get some sort of desktop browser build of the maple browser, so that we could figure out what part is a problem using requirejs in it. Otherwise, I do not have access to that type of TV to find out.

I am going to close this for now, but we can easily reopen if someone finds a way to get desktop maple browsers for testing and they have a test case that fails. Even with that, it may not be possible to fix depending on how far the maple browser is from other browsers in script loading support.
