### ISSUE TITLE
Error loading the same module twice

### ISSUE THREAD

**Issue by oscarotero** [jrburke/requirejs#1345]
I'm using codemirror with requirejs the same file is loaded twice depending of how it is called. There is an issue about this: https://github.com/codemirror/CodeMirror/issues/3234

Codemirror loads its own modules using relative paths, and requirejs cannot detect that these relative modules are the same than the ones I've configured and loaded previously.

**Comment by jrburke** [comment]
If you can set up a test project that shows the issue, that would help in suggesting a solution. My brief skim of the issue though is if there is a module ID that starts with "../" that is at the top of the module ID space, requirejs cannot normalize it correctly. It tries to be accommodating and still load it, but it will be a different module ID internally.

In a 3.0 version of requirejs I would probably just throw on this type of module ID, since it can lead to these problems. Normally setting a paths config so that the '../' is not needed fixes the issue, and is the recommended fix. However, if there is a sample project I can try, then I can give finer grained feedback.

**Comment by oscarotero** [comment]
Hi, sorry for the late response.
I've made a test that you can download here: https://www.dropbox.com/s/hnhpifrgrps650p/codemirror-requirejs.zip?dl=0

You can find three index.html loading codemirror in three different ways. The module-code need to know the mode before load the dependencies, to apply the right code mode to the editor.

The fact is if the paths of the modules are configured in `require.config` it does not works.

When I discovered this problem, I had even a case in which I was able to configure the paths and require could load all the modules right, but codemirror was downloaded twice (one by my module and other by the htmlmixed module), so the htmlmixed module was registered in a different instance of codemirror than I used. But I cannot reproduce now this behaviour. I'll keep investigating.

**Comment by jrburke** [comment]
For codemirror, since it has a full directory of modules with many internal dependencies, it is better to use the [packages config](http://requirejs.org/docs/api.html#packages) instead of paths config. 

paths config is best for smaller sets of modules that may not even need to be in their own directory. packages config lets you refer to the whole package as "codemirror" from the outside without needing to know its internals, except for the location of the "main" module for the package.

If I modify the index2 pathway to use this config:

```javascript
require.config({
  urlArgs: "bust=" +  (new Date()).getTime(), //for cache
  packages: [{
    name: "codemirror",
    location: "../bower_components/codemirror",
    main: "lib/codemirror"
  }]
});
```

and modify module-code2 to do this:

```javascript
define([
  "require"
], function (require) {
  return {
    init: function (textarea) {
      var mode = textarea.dataset.mode;

      require([
        "codemirror",
        'codemirror/mode/' + mode + '/' + mode
      ], function (codemirror) {
        var editor = codemirror.fromTextArea(textarea, {
          mode: mode
        });
      });
    }
  }
});
```

Then it works for me. Going to close as packages config as the recommendation. Feel free to continue discussion here.

**Comment by oscarotero** [comment]
Thank you so much for your help!
I didn't know the packages config. It's very useful.
Everything works fine now. :+1:
