### ISSUE TITLE
Load timeout for modules - When using 3G 

### ISSUE THREAD

**Issue by CoolArchTek** [jrburke/requirejs#1365]
I am getting Load timeout for modules when using 3G speed. Works good on WiFi. I even able to reproduce this on chrome developer tools using 'Regular 3g Speed' iPhone.

Here is my config. I even tried to double the waitSeconds still no use!! Any thoughts? 

require.config({
    baseUrl: '/mylibraries/javascript/library',
    paths: {
        'ga': (document.location.protocol.indexOf('https') === 0 ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga'
    },
    shim: {
        'bootstrap': {
            deps: ['jquery', 'domReady!']
        },
        'ga': {
            exports: '_gaq'
        },
        'jquery': {
            exports: 'jQuery'
        },
        'jquery.breakpoint': {
            deps: ['jquery'],
            exports: 'jQuery.event.special.breakpoint'
        },
        'jquery.gnCarousel': {
            deps: ['jquery'],
            exports: 'jQuery.fn.gnCarousel'
        },
        'jquery.menu': {
            deps: ['jquery'],
            exports: 'jQuery.fn.menu'
        },
        'jquery.mobile-carousel': {
            deps: ['jquery'],
            exports: 'jQuery.fn.mobileCarousel'
        },
        'jquery.watermark': {
            deps: ['jquery'],
            exports: 'jQuery.fn.watermark'
        },
        'underscore': {
            exports: '_'
        },
        'jquery.ui': {
            deps: ['jquery']
        }
    }
});

**Comment by johnrobertallan** [comment]
I'm experiencing a timeout issue for one module. however this seems to prevent all the other modules, which are not dependent on the timed out one from running. how can I have the other modules continue on?

**Comment by jrburke** [comment]
You can set [waitSeconds: 0](http://requirejs.org/docs/api.html#config-waitSeconds) to remove the timeout checking. Timing out is a global failure, since it can mean that the module that timed out is a dependency of other modules and those modules then would fail. A fresh, top level require([]) call after a failure should still work though.

The waitSeconds: 0 is the way to avoid the general issue on slow networks though. At some point the browser might give up on the script, but at least the timer in requirejs will not cause the timeout error.

**Comment by jrburke** [comment]
Oops, just saw #1372, so the separate top level require([]) may still be a problem. But waitSeconds: 0 is still good advice for disabling the requirejs timer.
