### ISSUE TITLE
Why is build.js not build.json

### ISSUE THREAD

**Issue by kamrenz** [jrburke/requirejs#1370]
It seems that the build.js file is really just a configuration file. I hadn't really thought about this until I switched to using WebStorm as an IDE. The IDE has confusion over what build.js is and that made me begin to wonder also. 

I can just save build.js as build.json, but I am wondering why it was chosen through all of the documentation to be build.js when it syntactically seems to just be JSON.

Any thoughts would be helpful.

**Comment by jrburke** [comment]
[Some of the config](https://github.com/jrburke/r.js/blob/master/build/example.build.js) can be functions, like onBuildWrite/onBuildRead, so json did not seem appropriate as the generic suggesion. If you also place () around the object literal, it might help the editor understand it is JS, might depend on the validation rules in place.

Closing as a discussion ticket, but feel free to continue discussion here.

**Comment by DevelopIntelligenceBoulder** [comment]
Thanks for the comment. I didn't realize there was onBuildWrite and onBuildRead functionality :)

**Comment by kamrenz** [comment]
Thanks. I didn't realize there was onBuildWrite and onBuildRead functionality :)

**Comment by kamrenz** [comment]
Syntactically, what does ( ) mean surrounding an object literal?

**Comment by jrburke** [comment]
I believe it converts it to an expression that is valid at the top level of a JS program. Depends on your linter though -- on one project that wants semicolons, it will still complain about not having an ending semicolon.

r.js internally wraps the build.js contents in () so that it evals correctly, and returns a result usable inside the optimizer.
