### ISSUE TITLE
Remove script from DOM

### ISSUE THREAD

**Issue by vaneshmali** [jrburke/requirejs#1388]
ReuireJS just adds a script tag to the page .
In traditional Web page every refresh or navigation o browser loads only needed files and unloads (or caches) others files 
Suppose you have a web site with 10 links and each link needs a different JS file ;
So if one user visits all the links the browser will load all 10 JS files just like you loaded them once ?
And suppose the user machine and browser don't support the load of the 10 files at once and will crashe at the end 
a RequireJS (AMD) solution just delays the problem not solving it in my sens

**Comment by Samlv9** [comment]
******************Your English Is So Good Good Up.******************

Why not use `rjs` combine them ?

**Comment by jrburke** [comment]
@Samlv9 let's not comment on the English level, but instead just ask for clarification if something is not clear. I am a native English speaker, but still find it hard to communicate my points clearly sometimes.

@vaneshmali knowing how best to tune for individual scripts vs bundles is very dependent on the app use case. As @Samlv9, the optimizer allows you to combine scripts if you need to. It can be helpful to avoid needing to bundle while in development, but often for final deployment some bundling can be useful.

If you find that if there is a script error, the error comes later, because the script tags are added as "async" tags, and you prefer it to fail sooner, perhaps blocking rendering: I personally find the async behavior more forgiving, might allow the page to still render, while allowing me to deal with an error and perhaps retry.

Going to close this as a discussion ticket, but feel free to continue discussion here. If you feel we did not quite address the question, feel free to add more detail.
