### ISSUE TITLE
Default plugin for all modules?

### ISSUE THREAD

**Issue by parris** [jrburke/requirejs#1390]
I'm trying to use es6 for all files in my project. It is getting a little tedious (and error prone) prefixing every file with "es6!". Is there a way to tell requirejs to use the es6 plugin unless we specify another plugin? That is use `es6!` unless we specify something like `hb!` or `text!`.

If this functionality doesn't currently exist, we may want to provide it. Here is a case for it:
If someone prefixes a file with es6 in one place and another person doesn't prefix that same file we get a really strange error and requirejs claims a timeout has occurred. It turns out this just due to not naming the file the same thing. Also, we want want to remove the mental overhead of thinking "is this an es6 module or not?".

**Comment by jrburke** [comment]
You can override [requirejs.load](https://github.com/jrburke/requirejs/blob/e6bc5e2838a8b17434c4a9440ea507310668ff89/require.js#L1853) to do an alternate loading strategy, like using an xhr and transpiling. [cajon](https://github.com/requirejs/cajon) does something like this if you want a model to follow.

For an optimizer build, I suggest transpiling first before calling the r.js optimizer for it to work in that environment.

No other plans for support for this besides that. [amodro-base](https://github.com/amodrojs/amodro-base) uses a different set of lifecycle steps for a loader to allow to make this sort of thing easier, so that is the longer term suggestion. However, right now the loaders generated from that project are not easy to consume yet.
