### ISSUE TITLE
I don't understand referencing modules

### ISSUE THREAD

**Issue by SetTrend** [jrburke/requirejs#1403]
I absolutely don't understand how the module path is to be provided for imports to work.

Most of the time while I'm editing TypeScript in Visual Studio 2015 I'm getting a red squiggly line and an error message telling me that module "x" could not be found. But there is no IntelliSense or whatsoever for creating the correct module name helping me in finding the right name to add to the require call.

Here's my problem: I'm writing code that's been used by different HTML pages residing in different directories. Parts of my TypeScript code also resides in separate directories.

So how am I supposed to reference all the different TypeScript/JavaScript libraries from within TypeScript code for it to work correctly in the end? How do I address it in TypeScript and how do I address it later when it's been called from within one of my HTML pages?

And how is jQuery supposed to fit into all this? The only way to reference jQuery is by writing:

    import $ = require("jquery");

But there is no such file with that name in my project. But any other term I'm using (e.g. "../../Scripts/jquery-2.1.4") brings back the red squiggly line again. So how's this all supposed to load at run-time?

I already read [How to Use RequireJS with jQuery](http://requirejs.org/docs/jquery.html) and [RequireJS Configuration options](http://requirejs.org/docs/api.html#config), but I still don't understand.

It becomes particularly hard to understand when it comes to deploying things. Because then I'll be using ".min.js" files, residing in yet another directory.

Please help.

**Comment by chrisknoll** [comment]
I can try, but other experts can chime in if I am not completely accurate:

I think of paths that take a module identifier (module ID) and guide me to the correct file path to load the module.  Based on configuration, I can have 

`````javascript
paths: {
  "jquery": "http://code.jquery.com/jquery-1.11.2.min"
}
`````

This means require ('jquery') will fetch it from that URL (note the absence of .js).  however a module gets resovled to a physical path, it will tag a .js at the end.  I can change the path to a different version of jquery (or even the non-minified version) and the loader will load this other URL when module 'jquery' is requested.

NORMALLY the module ID that you request (and the javascript that the module ID resolves to to load) becomes the 'official module ID' of that module for the duration of the page (think single page apps have a very long lifetime).  So this means that on one page you can load the module under one module ID name, and on another page it can be loaded under another module id (because the paths for each page make the different module IDs resolve to the same javascript code).  These types of modules (that take on the module ID of what requested them) is called an 'anonymous module' and is how most modules should be written.

jQuery is a special beast:  those devs are so important that they decided to hardcode the jQuery module id that defines the module to be 'jquery' such that if you try to define a path to that library that is something other than 'jquery' you'll get an AMD loader error saying that there is a duplicate module ID defined.  Here's why:  Consider the following path:

`````javascript
paths: {
  "j-Query": "http://code.jquery.com/jquery-1.11.2.min"
}
`````

If you requyre("j-Query") in code, the AMD will resolve that module ID to the URL to load the jquery 1.11.2 library and load it into the module space.  however, part of the jquery definition says 'call me jquery!'.  And the module loader is going to be like 'but you were requested as 'j-Query' and now i'm confused!  ERROR!  This module has 2 IDS! Duplicate! Duplicate!!'

But, there's a good reason for this: jquery is something that is reused across a wide variety of contexts.  If you want to write a module that uses jquery, what are you going to require()?  One dev says require('jQuery') another dev says require('j-query'), who wins?  Well the god damn authors of jQuery wins, that's who!  They force you to name your module to jquery 'jquery' and that's that.

On this note, you may want to make your own reusable components that can be referenced in different contexts, perhaps by different names (because you want to avoid name conflicts..from personal experience, calling a module 'chart' is not a good name).  So, here's what I do to define reusable modules that have their own inner-dependencies but I want to provide the 'unit' of functionality to external clients:

The directory structure looks like this:
/somedir/myModule.js
/somedir/myModule/subModuleA.js
/somedir/myModule/subModuleB.js
/somedir/myModule/subModuleC.js

From this, my paths config looks like this:
`````javascript
baseurl: "/js",
paths: {
  "theModule": "myModule"
}
`````

the myModule.js looks like this:
`````javascript
// myModule - this will load all modules at once
define(function() {
  var _moduleA = require("./myModule/subModuleA");
  var _moduleB = require("./myModule/subModuleB");
  var _moduleC = require("./myModule/subModuleC");

  return {
    moduleA: _moduleA,
    moduleB: _moduleB,
    moduleC: _moduleC
});

// elsewhere to load this module:
var moduleReference = require("theModule")


`````

So one thing you notice is that in the myModule.js, I have to put the sub-directory in the module name. This is where the module ID and physical directory begins to blur:  When the module "theModule" is requested it locates it in someDir/myModule.  Inside myModule.js, the require() calls are saying 'From where you find me, go down a directory and load the .js file subModuleA, B and C'.  Each of those modules will be given their own module ID, I believe it will be theModule/myModule/subModuleA, but you won't require() that module, you only need to require("theModule") and what that returns is the sub modules exposed as 3 properties of the main module "theModule".

I know this is confusing, but the best way to learn about how it works is to create a directory structure with some JS files in it, and do a require() to load one of the files, and watch your Chrome dev console to see what the actual URLs are requested.

I wish there was a better way to wrap whole subdirectories into packaged components, and I think 'packages' does what is needed there, but I'm not really too great with AMD yet..still learning.

**Comment by SetTrend** [comment]
**Thank you for your overwhelmingly informative and enlightening answer!**

Now I understand why jQuery behaves different from my modules.

So, if I defined my modules with a name - of if I had the RequireJS Optimizer concatenate a number of modules into a single file, I would then be confined to the pre-set module ID, wouldn't I?

**Comment by chrisknoll** [comment]
I'm not an expert on the optimizer, however, I believe that when the optimizer kicks off and you give it the root context to start optimizing, all those anonymous module IDs will be allocated a 'optimize-time' module id such that the code in the minified bundle (that is calling define() or require()) will find those modules in the local minified bundle and nothing gets loaded asynchronously (it's all pulled down int he one minified file).  There are ways of splitting an optimized build into several separate fragments such that you can split your minified bundle into logical groups, but I do not have a lot of experience with this.  The point is, tho, that the abstraction of a moduleID that separates it from the filesystem is somethign that allows you to refer to the moduleID of a module and not worry about if it's loaded asynchronously from a URL or if it was bundled into a optimized libary.

Again, best way of understanding how it works, is to just make something simple and optimize it up and see how ti works.  There's some good resources online as well, and I'd very much like to dig into it myself, but for now I work with un-optimized javascript for now as it doesn't really hinder me too much...but it is a skill that I need to pick up.

**Comment by chrisknoll** [comment]
But to better answer your question: yes as the optimizer runs, it will put moduleIDs into the optimized code, because only one JS file is goign to be loaded but it will expose multiple different moduleIDs that are loadable.

**Comment by SetTrend** [comment]
Thanks a lot Chris for enlightening me so tremendously on my question.
