### ISSUE TITLE
shim doesn't work for preloaded modules

### ISSUE THREAD

**Issue by oleg-amdocs** [jrburke/requirejs#1407]
Hi,

I am not sure is it a feature or bug, but I cannot force requirejs to load required module in the case I load all modules from one file. For example, I have the following code:

```html
<html>
<body>
<script>
    var require = {
        shim: {
            'dependent': ['dependency']
        }
    };
</script>
<script src="require.js"></script>
<script>
    /// line to remove:
    define('dependent', [], function () {});

    requirejs.onResourceLoad = function (context, map) {
        console.log('Loaded module: ' + map.name);
    };

    require(['dependent'], function () {
        console.log('requirejs finished');
    });
</script>
</body>
</html>
```
this code produces the following log:
```log
Loaded module: dependent
requirejs finished
```
but if I remove 'line to remove' the log will be:
```log
Loaded module: dependency
Loaded module: dependent
requirejs finished
```
(file 'dependent.js' exists, it is an empty module, it doesn't matter what it contains)

**Comment by jrburke** [comment]
Shim config is only for code that does not call define() to define a module. Mixing define() and shim will lead to inconsistent results, depending on load order and if this is a post-build step. In this case, since there is a define() already registered for the module, the shim config is not consulted.

The solution is to use either define() or shim, but not both for the same module ID.
