### ISSUE TITLE
Add requesting module name to "script error" message

### ISSUE THREAD

**Issue by mariusGundersen** [jrburke/requirejs#1422]
If a module cannot be loaded, and the server returns a 404, then requirejs reports a "script error" for the module name, but doesn't report which modules requested the module that couldn't be loaded. Adding this information to the error message would make it a lot simpler to track down issues. 

Since every module (using `define()`) has an explicit or implicit name, this should be relatively simple to add. It might be a problem with `require()` calls, but it would be a great step forward to at least get it to work with `define()` calls.

**Comment by neale-bpm** [comment]
@mariusGundersen and @jrburke Thanks for this happening.  I've just hit one of the old errors and thought... "surely this could have a useful message to tell me where the source of the problem is", and it turns out that 4 and bit years ago...  So. Thanks.  I'll update and ponder what has happened in the world of software since 2.1.5 was released  :-)
