### ISSUE TITLE
Add cache-busting parameter to sourceMappingURL

### ISSUE THREAD

**Issue by sergiopereiraTT** [jrburke/requirejs#1424]
It has been a constant problem for me and my team. Once in a while Chrome decides to not fetch the latest sourcemap and load a cached one, causing all sorts of confusion. It doesn't matter that the dev tools settings are telling Chrome to disable cache.

To be fair, this could be a Chrome bug but, regardless, having a way to tweak the output `sourceMappingURL` to include a cache buster would be very nice.

**Comment by noahpeters** [comment]
i use "urlArgs" when i call requirejs.config({"urlArgs": "....some cache busting version indicator...."})

**Comment by sergiopereiraTT** [comment]
I do to but it doesn't apply to the sourcemap urls at the bottom of the combined file.

**Comment by jrburke** [comment]
This would be different from urlArgs because urlArgs are something applied at runtime, where this stamping would be done at build time.

No plans to add this. The onBuildWrite build hook is called before the optimization is done, so that will not give you the source with the source map URL in it. Looks like it is best to use a post r.js build step process that opens up the .js files and modifies the source map URLs to add the kind of cache busting you prefer.

**Comment by chrisknoll** [comment]
Or set the no-cache flags on the webserver, the way god intended.
