### ISSUE TITLE
Exception in require can randomly cause define for other modules to fail

### ISSUE THREAD

**Issue by Lumaraf** [jrburke/requirejs#1440]
I have two modules A and B. B has a dependency on A. If both modules are loaded in parallel and the require call for module A throws an exception it can sometimes cause module B not to be defined.

If module A is loaded before B it will work fine. Otherwise if B is loaded first it will fail.

For testing make sure to not load it from local files an to disable the browser cache as it can make this harder to reproduce on successive tries.

# test.htm
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.20/require.js"></script>
<script>
	// the order of both calls can be changed, but this way it is a bit easier to reproduce
	require(['b'],function() {
		console.log('require b succesful');
	});
	require(['a'],function() {
		throw '';
	});
</script>
```

# a.js
```javascript
define(function() {
	console.log('a defined');
});
```

# b.js
```javascript
define(['a'],function() {
	console.log('b defined');
});
```

**Comment by chrisknoll** [comment]
Good test case, and this is something that should definitly be supported.  @jburke, what synchronization is used during a dependency chain load?  I havent seen the code, but id imagine that when a module is is requested via require() or part of a define(), a promise for the requested module is provided such that if another module is requested that is a dependency if anirher yet-to-be-resolved require(), the second require() will get the promise and not try to do the load.

I'm not sure what kind of race conditions you need to watchout for in javascript (it's single threaded, yes?) But this problem smells of race condition.

**Comment by jrburke** [comment]
This is definitely a bug. I am not sure yet how I will address it. The error handling pathway in the code could use some reworking. If you wanted an AMD loader that did not have this problem, I just tried [alameda](https://github.com/requirejs/alameda) with the example and it works, fires all the console messages.

Defining a requirejs.onError = function(err) {} helps, in that the console.logs do fire, but the error is lost then in that case, so not great either.

Some notes on the code: the issue is in check(), with its two paths for context.execCb(), this case follows the else, and just lets the error disrupt the control flow. Seems like the try/catch should always be there, but just route it different based on the factors involved.

Marking for 2.1.21 consideration, but may not make it depending on the scope of the fix.

**Comment by jrburke** [comment]
The change for this ticket was reverted as tracked in #1477 for v2.2.0. It was a bit clunky and ran into other problems. Unfortunately a proper fix means changing more of the internals, so I will leave this as closed, but definitely recognized as a shortcoming.

As mentioned above, [alameda](https://github.com/requirejs/alameda) does not have this problem, and is the kind of foundation I would want to use for a requirejs 3, so I suggest using that if you need an alternative.

**Comment by chrisknoll** [comment]
I would like to investigate migrating to alameda, but some of the require() semantics worries me.  Is there a migration guide?  Currently we do most of our module definitions as define(['mod1','mod2']), but sometimes we do the define( function(require, exports) {}) CJS wrapper sort of code, and I'm not sure if that is supported....

If you can do the define(function (require,exports) {} ) mode, does each call to require() within the module have to work using promises as well? Or are the 'local require' calls synchronous.

Finally, are the plugins (such as text! and css! ) compatable with almeda?

**Comment by jrburke** [comment]
Right now alameda passes all the tests in requirejs, except for some newer edge case fixes in requirejs, I just haven't updated the test copy in alameda for the work I'm doing for 2.2. After 2.2 is released, I'll update the test pass in alameda.

In general, the goal is to have compatibility with the basic mechanics of AMD support, just have updated underpinnings. So the different calls signatures for define() work the same. The promise from a require is just for async require([]) calls. Plugins should work the same too.

There are some things that are not supported, but those are edge APIs, not around the core AMD specs. See the readme for the full list, but basically right now, these are not supported, those tests do not pass:

* require.undef 
* onResourceLoad

**Comment by dgoldstein0** [comment]
is there any plan to fix this?  it's causing a lot of spam in my website's exception reporting and I think possibly leading to lots of other noisy bugs for us.

**Comment by jrburke** [comment]
Not likely to be fixed, if you can move to [alameda](https://github.com/requirejs/alameda) that would be best. As [this comment mentions](https://github.com/requirejs/requirejs/issues/1440#issuecomment-197112950), the error handling in requirejs is a bit clunky, hard to see a clear update path for it.

**Comment by dgoldstein0** [comment]
If I have time I'll look at the alameda docs; I'm partially wondering if #1477 is really that bad of a bug or not, since the description is a little sparse; if it's not a big concern for us, I'd rather just move to 2.1.23 which appears to have the fix for this.

My basic understanding though is that Alameda may be a viable alternative - provided we ship it with a promise polyfill for Internet Explorer - but we have some code that relies on onResourceLoad and a few other internals to track how long each module takes to load, which would probably have to be reworked.  It's definitely worth investigating for us but I don't know if I'll be able to get to it anytime soon.
