### ISSUE TITLE
Path plug-ins

### ISSUE THREAD

**Issue by DataTables** [jrburke/requirejs#1442]
I'm trying to find a way to load both the JS and CSS required for web component - I realise that [CSS is not supported](http://requirejs.org/docs/faq-advanced.html#css) by the core, but I was hoping to use the [require-css](https://github.com/guybedford/require-css) plug-in. That works okay, but I can't find a way to have a module name include both the JS and CSS.

I found that the `config.paths` option for a module could specify multiple files in an array, so I tried:

```js
        'datatables.net-bs': [
            'require-css!//nightly.datatables.net/css/dataTables.bootstrap.min',
            '//nightly.datatables.net/js/dataTables.bootstrap.min',
        ]
```

But the plug-ins operate on the module name, not the path. I had a look at the plug-ins API but can't see an option to add a plug-in at that point - is my reading of the documentation correct, or is that actually possible?

If it isn't, could anyone point me in the direction of how to do this?

I basically want to be able to do something like this:

```js
require( ['jquery', 'bootstrap', 'datatables.net-bs'], function ($, dt) {
    $('#myTable').DataTable();
} );
```

where `datatables.net-bs` will load the Bootstrap integration for DataTables (CSS and JS).

I could have the developer require both independently as different modules, but I can't see why you would ever want one without the other since they are interdependent and it would make their require line really verbose (particularly if they loaded a couple of the plug-ins for the software).

This is what I have tried: http://jsfiddle.net/coaqsjkv/  - note that the CSS "plug-in" is not resolved at the path level giving a 404.

**Comment by jrburke** [comment]
Right, it is best to keep the paths config to just mapping ID segments to path segments. I got this to work in the fiddle:

```javascript
require.config( {
    deps: [ 'require-css' ],
    paths: {
        'require-css': '//cdnjs.cloudflare.com/ajax/libs/require-css/0.1.8/css.min',
        'bootstrap': '//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min',
        'jquery': '//code.jquery.com/jquery-2.1.4.min',
        'datatables.net': '//nightly.datatables.net/js/jquery.dataTables',
        'datatables-css': '//nightly.datatables.net/css/jquery.dataTables.min'
        'datatables.net-bs': [
            'require-css!//nightly.datatables.net/css/dataTables.bootstrap.min',
            '//nightly.datatables.net/js/dataTables.bootstrap.min',
        ]
    }
} );

require( ['jquery', 'require-css!bootstrap', 'datatables.net-bs', 'require-css!datatables-css'], function ($, dt) {
    $('#myTable').DataTable();
} );

```

But if you wanted it to work so that the user only had to specify one ID for the dependencies, then it is best to use a loader plugin for that. So that the user could do a 'webc!datatable', and the webc plugin would know how to do a require([]) call to both resources. This also likely assumes a standardized JS/CSS file layout in the component. 

Or (what I would try to do if the constraints allow), create something like a 'datatables-all' module that depends on the two resources, and ask for consumers to use that module instead of the individual pieces.

That is the extent of the options though. There is no config option to try to request multiple IDs for a single ID.

Closing as a discussion ticket, feel free to continue discussion here.
