### ISSUE TITLE
Possible to define a module asynchronously?

### ISSUE THREAD

**Issue by moscartong** [jrburke/requirejs#1446]
Currently when we define a module, we do:
```JavaScript
define(['foo', 'bar'], function(foo, bar) {
    //do something here
    return { ... }
});
```

What if I need to do something that takes some times inside the function and give back the result later via callback or promise? For example:
```JavaScript
define(['foo', 'bar'], function(foo, bar) {
    //go fetch something from the server, etc
    return new Promise( ... );
});
```

Is this possible with current implementation or with the help of some other library/plguins?

**Comment by chrisknoll** [comment]
Just do your normal async calls in your module, but if you need to monitor if the module has all the async things completed, you should define a 'module scoped' variable to store a promise, and then chain all your asynchronous operations to this module scoped variable.

~~~~~ javascript
define(['foo', 'bar'], function(foo, bar) {
  var modulePromise;

    //do something asynchronous here, either some AJAX call, or use setTimeout() to call it as a separate invocation
  modulePromse = $ajax() // etc
    return { ... }
});
~~~~

All the functions that require this asynchronous work to be completed should check for this promise first using the promise.when() pattern. If you have other modules that depend on this module's async work, you should expose the modulePromise as a module exported property so that others can do things like 

~~~~~javascript
var myModule = require('myModule');
myModule.modulePromise.then(function () {
});

`````

Something like that.

**Comment by jrburke** [comment]
Right, for a regular module the only option is to return a Promise for the module value, but then modules that use that dependency need to do promise.then() when wanting to use the promise result. There is no magic to support treating the exported promise as blocking the load definition for the module. 

You could make a loader plugin for that case, but it also needs to be able to operate in r.js build environments, not running in the browser. Loader plugins do allow delaying the loaded state for a module on some async process.

Closing as a discussion ticket, feel free to continue discussion here.
