### ISSUE TITLE
Access requirejs modules outside requirejs

### ISSUE THREAD

**Issue by MichaelJCole** [jrburke/requirejs#1449]
Hey, there's a module packaged with require.js:

https://github.com/andyet/SimpleWebRTC/blob/master/simplewebrtc.bundle.js

I want to access some of these modules in Meteor.js (which does not have support for require.js)

I'm trying this, but it's not working:
```
required = {};
Meteor.startup(function() {
  require(
    ['hark'],
    function(hark) {
      required.hark = hark;
    }
  );
});

```
I'm getting this error:
```
Uncaught Error: Mismatched anonymous define() module:
```

If I run this command in the console, I get something out of require.js, which might lead to hark:
```
require(['hark'], function(hark) { console.log(hark); });
```

Any suggestions?

Thanks!

**Comment by jrburke** [comment]
I had a brief conversation with a colleague who was trying to use meteor with AMD modules, but it was really hard to get it to work since meteor's model is so different for loading code. In short I do not suggest trying to mix the models, as I think it will be difficult.

If you did want to get it to work I think it is best to ask the meteor community about it. I believe they will need to work out something better anyway given that ES2015 modules are more similar to the AMD/CJS model as far as dependency tracing. I'm going to close this then, since I am not aware of a way to get it to work well.

**Comment by MichaelJCole** [comment]
Hey @jrburke thanks for the feedback.  It's a sticky wicket.

The simplest thing that could possibly work was to include them again.  It adds about 100k of redundant download to my app.

```
-rw-r--r-- 1 michael michael 389862 Nov 13 20:17 simplewebrtc.bundle.js <-- one copy of every thing
-rw-r--r-- 1 michael michael  19939 Nov 14 10:03 attachmediastream.bundle.js <-- extra copies
-rw-r--r-- 1 michael michael  29341 Nov 14 10:39 getscreenmedia.bundle.js
-rw-r--r-- 1 michael michael  21478 Nov 14 10:02 getusermedia.bundle.js
-rw-r--r-- 1 michael michael   8187 Nov 14 10:04 hark.bundle.js
```

I'm still not sure why 'hark' cannot be accessed from inside `simplewebrtc.bundle.js`.

For a client-side JS package manager it seems like "you have to download it again" would be an API bug.

This is different than npm's require which duplicates the world because disk/bandwidth is essentially free in development.

On the client, when Require loads the code, there's a DI container.  I just want a function to reach into that container and pluck out a working module.
