### ISSUE TITLE
How to add custom request headers to calls that load scripts

### ISSUE THREAD

**Issue by rvnath** [jrburke/requirejs#1455]
As per the security audit done on my web app, I am expected to send security related headers in requests that load script files.  http://content-security-policy.com/.  As per this, I need to send a request header like 

Directive | Example Value | Description
----------- | ------------------- | -----------------
script-src | 'self' js.example.com | Defines valid sources of JavaScript. 

I am using RequireJS to load the script files.  So, is there a way I can tell requirejs to use specific headers while sending request to fetch the script files...

**Comment by jrburke** [comment]
My understanding is that those CSP headers are sent by the server, in the response to the requests issued by the server, specifically, the server should send it with the HTML document used for the page. The server should be responsible for those headers, so that the proper level of security is set.

So there should not be a need to set the CSP request headers client side with requirejs. Since requirejs uses script tags to fetch the .js files, it cannot set request headers anyway.

Closing as a discussion ticket, feel free to continue discussion here though.
