### ISSUE TITLE
Trouble downloading script

### ISSUE THREAD

**Issue by ZyshchykMaksim** [jrburke/requirejs#1458]
Hi, I really need your help.
In advance sorry for my english.

I'm always there is an error on the first run and clear the cache:
**require.js: 1926 GET http: // localhost: 10955 / Scripts / jquery.js
require.js: 165 Uncaught Error: Script error for: jquery**

I'm using ASP.NET MVC.
There is a basic Layout     

 ```<script data-main='Scripts/config' src="@Scripts.Url("~/Scripts/require.js")"></script>```
    

File config.js
```

requirejs.config({
    urlArgs: "v=" + (new Date()).getTime(),
    shim: {
        'bootstrap': {
            deps: ['jquery']
        },
        'spinner': {
            deps: ['jquery']
        },
        'redirect': {
            deps: ['jquery']
        },
        'telefonica': {
            deps: ['jquery']
        },
        'datatables': {
            deps: ['jquery']
        }
    },

    paths: {
        jquery: 'jquery-2.1.4',
        bootstrap: 'bootstrap.min',
        knockout: 'knockout-3.3.0',
        spinner: 'spinner',
        domReady: 'domReady',
        redirect: 'redirect',
        datatables: 'DataTables/jquery.dataTables',
    }
});
```
Module
```define(['jquery', 'modules/timeout_redirect_page'], function ($, globalRedirect) {
    $(document).ready(function () {      
        ...
    });
});```

Download module:      ```  require(['pages/start']);```

Thanks!

**Comment by jrburke** [comment]
As long as `require(['pages/start'])` is done inside the scripts/config call, then I expect it to work. If the `require(['pages/start'])` is done outside of that script tag, then it can be that config.js will not be loaded before the loader starts to fetch the dependencies for pages/start. In that case it is best to do something like this instead, to make sure config is loaded first:

```html
<script src="@Scripts.Url("~/Scripts/require.js")"></script>
<script>
requirejs.config({baseUrl: 'Scripts'});
require(['config'], function() { require(['pages/start']); });
</script>
```

I believe that is the issue since the error is for 'jquery.js' and not 'jquery-2.1.4.js', looks like the config is not applied when the tracing of the pages/start starts. So closing, but feel free to continue discussion here.
