### ISSUE TITLE
optimizer breaking code

### ISSUE THREAD

**Issue by adamjimenez** [jrburke/requirejs#1474]
see:
https://github.com/firebase/firepad/issues/221

This line:
```
this.aceRange = ((_ref = ace.require) != null ? _ref : require)("ace/range").Range;
```

Is getting optimised to:
```
this.aceRange==null&&(this.aceRange=(n=ace.require)!=null?n:require("ace/range").Range
```

Which ends up turning the value of this.aceRange into ace.require instead of ace.require("ace/range").Range

**Comment by jrburke** [comment]
What version of the r.js optimizer in play, and what is the ["optimize" setting](https://github.com/jrburke/r.js/blob/master/build/example.build.js#L99) when used with it? Hopefully it is the latest r.js release and "optimize": "uglify2". If not, it would be good to try that combination.

This would be an issue with the version of uglifyjs used in the optimizer, so it will help to identify what version is being used.

**Comment by adamjimenez** [comment]
optimize setting is left to default.

from npm -g ls:
├── requirejs@2.1.22
└─┬ uglify-js@2.6.1

**Comment by jrburke** [comment]
OK, I expect setting "optimize": "uglify2" in the build options that will get rid of the problem. If you can confirm that fixes the issue, that would help conclude the issue.

I filed https://github.com/jrburke/r.js/issues/883 to track just setting "uglify2" as the default in the next release since it is actively getting fixes and the 1.x uglifyjs series is way behind the times.

**Comment by adamjimenez** [comment]
Thanks. I tried that and it works. I agree that uglify2 should be the default.

**Comment by jrburke** [comment]
Great, closing this one, tracking the default switch in jrburke/r.js#883.
