### ISSUE TITLE
node ID compatibility should be enabled for CommonJS modules

### ISSUE THREAD

**Issue by jochenberger** [jrburke/requirejs#1476]
I have a web application that uses AMD modules with Requirejs. Now, I want to add some modules from a CommonJS library (deep-equal (https://github.com/substack/node-deep-equal)). i wrapped them in CommonJS wrappers (http://requirejs.org/docs/commonjs.html#manualconversion) and added them to the packages configuration (http://requirejs.org/docs/api.html#packages).
If I require `deep-equal`, the `index.js` is loaded from `${require.baseUrl}/deep-equal/index.js`. But when `index.js` calls ` require('./lib/keys.js');`, Requirejs tried to load `${require.baseUrl}/../deep-equal/lib/keys.js` (not literally, but that's the effective URI).
If I enable `nodeIdCompat`, it works as expected, but it affects other URIs that must not be changed.
I think that `nodeIdCompat` should automatically be enabled for files that are contained in a `packages` configuration.

**Comment by jrburke** [comment]
No plans to do this: not all uses of node_modules modules are a result of package config, the developer could have used something like [adapt-pkg-main](https://github.com/jrburke/adapt-pkg-main) to set up the use of the node_modules modules. So getting an accurate read on when to apply the setting would be hard to do.

Longer term, I want to get rid of the direct URL support in the loader, since I view it as a mistake long term to support it -- all the dependencies should be module IDs not URLs. It solves some build/portability issues too. When that happens, it may make sense to integrate the node ID compatibility always. However that sort of change would not be done until a major version rev.

So the suggestion is to avoid the use of direct URLs, set up paths config for those things instead, and then it should be easier to use the node ID compatibility.
